rules:
  mixins-before-declarations:
    - 2
    -
      exclude:
        - mobile
        - tablet
        - desktop
  property-sort-order:
  - 1
  -
    order: 'concentric'
  class-name-format:
  - 2
  -
    convention: 'hyphenatedbem'
  nesting-depth:
    - 1
    - max-depth: 4