import common from './common';

export default {
  meta: {
    description: 'Front-end developer, developing apps and web pages',
    keywords: 'React, Node, Gatsby, Front-end, developer, API',
  },
  'home.title': 'Home',
  'home.headline': 'Web Developer',
  'home.greet': `Hello, I am ${common.profileName}!`,
  'home.about': `I'm a Web Developer, I work with Front-end creating apps and web pages.
  I participate in events about technology and I like to study productivity and communication, it helps me stay organized and collaborative.`,
  'home.experience': 'I develop projects mostly with JavaScript using React and Node.',
  'home.personalProjects': 'personal projects',
  'projects.title': 'Projects',
  'projects.description': 'Some of my featured projects, see more on my',
  'projects.gatsbyCourse.title': 'Gatsby Course',
  'projects.gatsbyCourse.subtitle': 'Build your personal website using React',
  'projects.ticTacPorg.title': 'Tic-tac-porg',
  'projects.ticTacPorg.subtitle': 'Play tic-tac-toe with Star Wars theme',
  'projects.memepool.title': 'Memepool',
  'projects.memepool.subtitle': 'Discord bot that play meme sounds',
  'projects.westworldIntroCreator.title': 'Westworld Intro Creator',
  'projects.westworldIntroCreator.subtitle': 'Create your own Westworld opening',
  'projects.stack': 'stack',
  'stack.title': 'Stack',
  'stack.description': 'I have experience with many modern tools, I select them for my projects depending on the scenario.',
  'stack.stackShare': 'Here is my stack on StackShare:',
  'stack.posts': 'posts',
  'posts.title': 'Posts',
  'posts.learnReact.title': 'Learn React easily with this rule',
  'posts.learnReact.subtitle': 'Make it fun',
  checkOut: 'Check out my',
  ...common,
};
